# Generated by Django 4.2 on 2023-04-09 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_remove_filemodel_success_profiletask_success_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletask',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 16, 16, 53, 9, 154168, tzinfo=datetime.timezone.utc)),
        ),
    ]
