# Generated by Django 4.2 on 2023-04-18 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_profiletask_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletask',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 11, 54, 53, 398063, tzinfo=datetime.timezone.utc)),
        ),
    ]
